// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSf7hFp6g-76Bc7F9QHNHwW6EZ-XKaAKs',
    appId: '1:1023952059564:web:f034bbc0167365e1d8b309',
    messagingSenderId: '1023952059564',
    projectId: 'muet-offical-cbc41',
    authDomain: 'muet-offical-cbc41.firebaseapp.com',
    storageBucket: 'muet-offical-cbc41.appspot.com',
    measurementId: 'G-8JBJ4S2CCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3vxDlpdcOtNX48siIy2YB6k-SPYvI0kU',
    appId: '1:1023952059564:android:8eb9a2c9c12537f3d8b309',
    messagingSenderId: '1023952059564',
    projectId: 'muet-offical-cbc41',
    storageBucket: 'muet-offical-cbc41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtjdsjkZ1b3XFjvimm4KzmWAeT0oubjKU',
    appId: '1:1023952059564:ios:1475b3a7e0896766d8b309',
    messagingSenderId: '1023952059564',
    projectId: 'muet-offical-cbc41',
    storageBucket: 'muet-offical-cbc41.appspot.com',
    iosBundleId: 'com.muet.muetAppAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtjdsjkZ1b3XFjvimm4KzmWAeT0oubjKU',
    appId: '1:1023952059564:ios:1475b3a7e0896766d8b309',
    messagingSenderId: '1023952059564',
    projectId: 'muet-offical-cbc41',
    storageBucket: 'muet-offical-cbc41.appspot.com',
    iosBundleId: 'com.muet.muetAppAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSf7hFp6g-76Bc7F9QHNHwW6EZ-XKaAKs',
    appId: '1:1023952059564:web:a5d2d492b6c55da9d8b309',
    messagingSenderId: '1023952059564',
    projectId: 'muet-offical-cbc41',
    authDomain: 'muet-offical-cbc41.firebaseapp.com',
    storageBucket: 'muet-offical-cbc41.appspot.com',
    measurementId: 'G-FD7X0FQFQ4',
  );
}
